name: Dispatch update - CompetitionPCing

on: 
  push:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch update event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ECC-BFMC/CompetitionPCing
        event-type: update-subtree-Servers
