name: Update subtree

on: 
  repository_dispatch:
    types: [update-subtree-servers]

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Set Git identity
      run: |
        git config --global user.email "rares.lemnariu@ro.bosch.com"
        git config --global user.name "BFMC Rares Lemnariu"

    - name: Pull changes from subtree
      run: |
        git subtree pull --prefix=servers git@github.com:ECC-BFMC/Shared.git servers --squash
        git push

