name: Pull Data From Shared

on: 
  repository_dispatch:
    types: [Pull-Data-Changes-Computer]
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Set Git identity
      run: |
        git config --global user.email "rares.lemnariu@ro.bosch.com"
        git config --global user.name "BFMC - Rares Lemnariu"
    
    - name: Add source to the commit.
      run: |
        git subtree pull --prefix=servers git@github.com:ECC-BFMC/Shared.git servers
        git commit --amend -m "Traceback: FromPull"
        git push

        