name: Dispatch update - Computer

on: 
  push:

jobs:
  dispatch:
    if: github.event.commits[0].message != 'Automated update from GitHub Actions - CompetitionPCing'
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch update event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ECC-BFMC/Computer
        event-type: update-subtree-servers
